name: Nix Flake Validation
on:
  pull_request:
  push:
    branches:
jobs:
  check:
    runs-on: ubuntu-latest
    if: false
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          source ~/.nix-profile/etc/profile.d/nix.sh
      - name: Verify Nix installation
        run: /home/runner/.nix-profile/bin/nix --version  # Check if Nix is available
      - name: Run Nix Flake Check
        run: /home/runner/.nix-profile/bin/nix --extra-experimental-features nix-command --extra-experimental-features flakes flake check
